<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>

	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Authors>DotJEM</Authors>
	  <Copyright>Copyright © DotJEM 2023</Copyright>
	  <Description></Description>
	  <IncludeSymbols>False</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>

	  <AssemblyName>$(MSBuildProjectName)</AssemblyName>
	  <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>

	  <Version></Version>
	  <PackageVersion></PackageVersion>
	  <InformationalVersion></InformationalVersion>
	  <PackageVersion></PackageVersion>
	  <AssemblyVersion></AssemblyVersion>
	  <FileVersion></FileVersion>

	  <PackageIcon>avatar.png</PackageIcon>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SqlServer\Statements\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="SqlServer\Statements\*.sql" TemplateClass="SqlTemplates" />
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.35" />
		<PackageReference Include="DotJEM.SourceGen.TemplateGenerator" Version="0.1.13-beta001" />
		<PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\avatar.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
